# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
# Persistent Volume Claim (default storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# Nexus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
---
# Nexus Service
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32001

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
  labels:
    app: nexus
    type: nexus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nexus-data"
